apiVersion: v1
kind: Service
metadata:
  name: iris-svc
  labels:
    app: iris-svc
spec:
  clusterIP: None
  ports:
  - port: 51773
    name: superserver
  - port: 52773
    name: webserver
  selector:
    app: iris
